-- ============================================================
-- STEP 1: Run this block first in Supabase SQL Editor
-- Creates the table and RLS policy
-- ============================================================

CREATE TABLE IF NOT EXISTS school_profiles (
  school_id                  TEXT PRIMARY KEY,
  name                       TEXT NOT NULL,
  official_acceptance_rate   NUMERIC NOT NULL,
  acceptance_rate_source_year TEXT NOT NULL,
  sat_25th                   INTEGER,
  sat_75th                   INTEGER,
  act_available              BOOLEAN DEFAULT FALSE,
  act_25th                   INTEGER,
  act_75th                   INTEGER,
  avg_enrolled_gpa_unweighted NUMERIC,
  cds_factor_weights         JSONB,
  source_url                 TEXT,
  notes                      TEXT,
  category                   TEXT,
  match_score                INTEGER,
  location                   TEXT,
  deadline                   TEXT,
  round                      TEXT,
  why_fit                    TEXT,
  key_factor                 TEXT,
  strength_alignment         TEXT,
  region                     TEXT,
  updated_at                 TIMESTAMPTZ DEFAULT NOW()
);

-- Public read policy (no auth required to view schools)
ALTER TABLE school_profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read school_profiles" ON school_profiles;
CREATE POLICY "Public read school_profiles" ON school_profiles
  FOR SELECT USING (true);

-- ============================================================
-- STEP 2: Run this block separately AFTER Step 1 succeeds
-- Inserts all 53 school profiles (just click Run, no RLS prompt)
-- ============================================================

-- Upsert all school profiles
INSERT INTO school_profiles (
  school_id, name, official_acceptance_rate, acceptance_rate_source_year,
  sat_25th, sat_75th, act_available, act_25th, act_75th,
  avg_enrolled_gpa_unweighted, cds_factor_weights,
  source_url, notes, category, match_score, location,
  deadline, round, why_fit, key_factor, strength_alignment, region
) VALUES
  ('rec-mit', 'Massachusetts Institute of Technology (MIT)', 4.6, '2025-2026', 1520, 1580, TRUE, 35, 36, 3.98, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Standardized test scores":"Very Important","Application Essay":"Very Important","Recommendation":"Very Important","Character/Personal Qualities":"Very Important","Extracurricular Activities":"Very Important","Talent/Ability":"Very Important","Interview":"Considered","First generation":"Considered","Volunteer work":"Considered"}'::jsonb, 'https://ir.mit.edu/cds-2023-24', 'Standardized tests required (SAT or ACT). Holistic review evaluating deep quantitative mastery, maker initiative, and alignment with MIT mission.', 'reach', 96, 'Cambridge, MA, USA', 'Nov 1', 'Early Action (EA)', 'World-leading computing & engineering labs aligned with your {MAJOR} portfolio. Evaluates deep mathematical problem solving and distinctive maker spike.', 'STEM project portfolio, Olympiad/research depth, and math/science recommendation letters.', 'very_high', 'us'),
  ('rec-stanford', 'Stanford University', 3.8, '2024-2025', 1500, 1580, TRUE, 34, 36, 3.96, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Standardized test scores":"Very Important","Application Essay":"Very Important","Recommendation":"Very Important","Extracurricular Activities":"Very Important","Talent/Ability":"Very Important","Character/Personal Qualities":"Very Important","Interview":"Considered","First generation":"Considered"}'::jsonb, 'https://ucomm.stanford.edu/cds/2023-2024', 'Holistic review placing extraordinary weight on intellectual vitality and authentic character.', 'reach', 94, 'Stanford, CA, USA', 'Nov 1', 'Restrictive Early Action (REA)', 'Silicon Valley proximity and interdisciplinary tech-innovation culture.', 'Intellectual vitality essay and distinctive extracurricular leadership.', 'very_high', 'us'),
  ('rec-cmu', 'Carnegie Mellon University', 11.7, '2024-2025', 1510, 1570, TRUE, 34, 36, 3.95, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Standardized test scores":"Very Important","Extracurricular Activities":"Very Important"}'::jsonb, 'https://www.cmu.edu/ira/CDS/index.html', 'Premier pure computing and engineering curriculum with direct department admission.', 'reach', 95, 'Pittsburgh, PA, USA', 'Jan 3', 'Regular Decision (RD)', 'Premier pure computing and engineering curriculum with direct department admission.', 'Advanced math proficiency and coding project depth.', 'very_high', 'us'),
  ('rec-umich', 'University of Michigan', 17.7, '2023-2024', 1360, 1530, TRUE, 31, 35, 3.9, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important","Character/Personal Qualities":"Very Important"}'::jsonb, 'https://obp.umich.edu/campus-statistics/common-data-set/', 'High rigor public research university; out-of-state pool is exceptionally competitive.', 'target', 92, 'Ann Arbor, MI, USA', 'Nov 1', 'Early Action (EA)', 'World-class academic powerhouse for {MAJOR}. Highly competitive out-of-state and international admissions pool.', 'Demonstrated rigor in advanced math/science and compelling Community Contribution essay.', 'high', 'us'),
  ('rec-gatech', 'Georgia Institute of Technology', 17, '2024-2025', 1380, 1540, TRUE, 31, 35, 3.91, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important","Extracurricular Activities":"Very Important"}'::jsonb, 'https://irp.gatech.edu/common-data-set', 'Technological institute requiring rigorous math/science background and hands-on portfolio.', 'reach', 93, 'Atlanta, GA, USA', 'Oct 15', 'Early Action 1 (EA1)', 'Premier technological research institute with stellar co-op opportunities.', 'Demonstrated quantitative excellence and applied engineering initiatives.', 'very_high', 'us'),
  ('rec-purdue', 'Purdue University', 50.3, '2023-2024', 1210, 1470, TRUE, 27, 34, 3.78, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Standardized test scores":"Important","Application Essay":"Important"}'::jsonb, 'https://www.purdue.edu/datadigest/', 'Applying by the Nov 1 Early Action priority deadline is crucial for competitive STEM majors.', 'target', 92, 'West Lafayette, IN, USA', 'Nov 1', 'Early Action (EA)', 'World-renowned engineering and STEM programs with strong global ROI and industry placement.', 'Applying by Nov 1 Early Action priority deadline is strictly essential.', 'very_high', 'us'),
  ('rec-uiuc', 'University of Illinois Urbana-Champaign (UIUC)', 42.4, '2024-2025', 1340, 1530, TRUE, 29, 34, 3.85, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Extracurricular Activities":"Important"}'::jsonb, 'https://dmi.illinois.edu/stuenr.htm', 'Direct-to-major admission for Grainger Engineering and computer science majors.', 'target', 91, 'Urbana, IL, USA', 'Nov 1', 'Early Action (EA)', 'Superb departmental faculty and vast computing infrastructure.', 'Direct-to-major essay specificity and balanced quantitative coursework.', 'high', 'us'),
  ('rec-pennstate', 'Penn State University', 61, '2024-2025', 1160, 1370, TRUE, 26, 31, 3.65, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important"}'::jsonb, 'https://opair.psu.edu/institutional-research/common-data-set/', 'Large Big Ten research campus with substantial engineering and agricultural colleges.', 'target', 84, 'University Park, PA, USA', 'Nov 1', 'Early Action (EA)', 'Prominent Big Ten research institution. Offers strong resources and industry recruitment in {MAJOR}.', 'Consistent senior-year grades and applying early to the main University Park campus.', 'moderate', 'us'),
  ('rec-msu', 'Michigan State University', 83, '2024-2025', 1100, 1320, TRUE, 23, 29, 3.62, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important"}'::jsonb, 'https://opb.msu.edu/functions/institution/cds.html', 'Accessible Big Ten research university with honors college pathways.', 'safety', 86, 'East Lansing, MI, USA', 'Nov 1', 'Early Action (EA)', 'Top-tier undergraduate resources, extensive international support, and broad major flexibility.', 'Early application submission and meeting core high school coursework distribution.', 'high', 'us'),
  ('rec-asu', 'Arizona State University (ASU)', 89, '2023-2024', 1120, 1360, TRUE, 22, 29, 3.54, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important"}'::jsonb, 'https://uoia.asu.edu/data/common-data-set', 'Assured admissions criteria based on unweighted core GPA and course competency.', 'safety', 90, 'Tempe, AZ, USA', 'Rolling', 'Rolling Admission', '#1 in Innovation with high-capacity engineering and business programs, welcoming diverse academic trajectories.', 'Meeting standard competency requirements in math and laboratory sciences.', 'high', 'us'),
  ('rec-oregonstate', 'Oregon State University', 77.3, '2024-2025', 1080, 1320, TRUE, 21, 28, 3.61, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important"}'::jsonb, 'https://institutionalresearch.oregonstate.edu/common-data-set', 'Strong Pacific Northwest STEM and forestry research institution.', 'safety', 87, 'Corvallis, OR, USA', 'Feb 1', 'Regular Decision', 'Respected research university with strong STEM pathways and practical co-op experiences.', 'Demonstrated interest and completion of high school graduation prerequisites.', 'high', 'us'),
  ('rec-uta', 'University of Texas at Arlington (UTA)', 79.9, '2024-2025', 1040, 1260, TRUE, 20, 26, 3.48, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important"}'::jsonb, 'https://www.uta.edu/analytics/common-data-set', 'Carnegie R1 high research activity in Dallas-Fort Worth metro area with accessible criteria.', 'safety', 89, 'Arlington, TX, USA', 'Rolling', 'Rolling Admission', 'High-access Carnegie R1 research university in the Dallas-Fort Worth metroplex with very favorable tuition and admission rates.', 'Direct submission of transcripts and English proficiency proof.', 'high', 'us'),
  ('rec-cornell', 'Cornell University', 8, '2024-2025', 1450, 1560, TRUE, 34, 36, 3.9, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important","Recommendation":"Very Important","Extracurricular Activities":"Important"}'::jsonb, 'https://irp.cornell.edu/our-university/institutional-research/common-data-set', 'Ivy League with direct-to-college admissions; each school (Engineering, Arts & Sciences, etc.) has its own standards.', 'reach', 94, 'Ithaca, NY, USA', 'Nov 1', 'Early Decision (ED)', 'Ivy League depth with world-class {MAJOR} faculty and strong industry recruiting pipelines in NYC and Silicon Valley.', 'College-specific essays, rigor of senior-year coursework, and letters of recommendation.', 'very_high', 'us'),
  ('rec-northwestern', 'Northwestern University', 7.5, '2024-2025', 1500, 1570, TRUE, 34, 36, 3.92, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important","Extracurricular Activities":"Very Important","Character/Personal Qualities":"Very Important"}'::jsonb, 'https://www.northwestern.edu/institutional-research/data-and-statistics/common-data-set.html', 'Highly interdisciplinary with strong emphasis on research, entrepreneurship, and the Weinberg Core.', 'reach', 95, 'Evanston, IL, USA', 'Nov 1', 'Early Decision (ED)', 'Top-tier interdisciplinary research environment. {MAJOR} students benefit from McCormick School of Engineering and Kellogg proximity.', '"Why Northwestern" supplemental essay depth and demonstrated intellectual curiosity.', 'very_high', 'us'),
  ('rec-duke', 'Duke University', 5.7, '2024-2025', 1510, 1570, TRUE, 34, 36, 3.92, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important","Extracurricular Activities":"Very Important","Character/Personal Qualities":"Very Important"}'::jsonb, 'https://ir.duke.edu/common-data-set', 'Strong emphasis on authentic passion, research engagement, and Duke-specific community fit.', 'reach', 95, 'Durham, NC, USA', 'Nov 1', 'Early Decision (ED)', 'Research-forward culture with exceptional {MAJOR} resources and close-knit undergraduate community.', 'Authentic passion demonstrated through sustained EC commitment and strong supplemental essays.', 'very_high', 'us'),
  ('rec-jhu', 'Johns Hopkins University', 5.1, '2024-2025', 1510, 1580, TRUE, 34, 36, 3.9, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important","Extracurricular Activities":"Very Important"}'::jsonb, 'https://oir.jhu.edu/common-data-set/', 'Premier research university — undergraduate research culture is core to identity.', 'reach', 95, 'Baltimore, MD, USA', 'Nov 1', 'Early Decision (ED)', 'World #1 in research output with deep {MAJOR} lab access and a culture of undergraduate intellectual independence.', 'Demonstrated independent research or project initiative and compelling academic narrative.', 'very_high', 'us'),
  ('rec-northeastern', 'Northeastern University', 5.6, '2024-2025', 1490, 1560, TRUE, 34, 36, 3.89, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important","Extracurricular Activities":"Important"}'::jsonb, 'https://www.northeastern.edu/institutional-research-analytics/common-data-set/', 'Famous cooperative education (co-op) program placing students in industry every 6 months.', 'reach', 93, 'Boston, MA, USA', 'Nov 1', 'Early Action (EA)', 'World-renowned co-op program embeds {MAJOR} students directly in top-tier companies, providing unmatched pre-graduation industry experience.', 'Demonstrated career intentionality and professional initiative in extracurriculars.', 'very_high', 'us'),
  ('rec-ucla', 'University of California, Los Angeles (UCLA)', 9, '2024-2025', 1290, 1530, TRUE, 29, 35, 3.9, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important","Extracurricular Activities":"Important"}'::jsonb, 'https://apb.ucla.edu/campus-statistics/common-data-set', 'Holistic review via 8 Personal Insight Questions; GPA calculated by UC system scale.', 'reach', 94, 'Los Angeles, CA, USA', 'Nov 30', 'UC Application Deadline', 'Top-ranked public university with world-class {MAJOR} faculty, Silicon Beach proximity, and massive alumni network.', '8 UC Personal Insight Questions — depth, authenticity, and evidence of impact.', 'very_high', 'us'),
  ('rec-ucberkeley', 'University of California, Berkeley (UC Berkeley)', 11, '2024-2025', 1310, 1530, TRUE, 29, 35, 3.89, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important","Extracurricular Activities":"Important"}'::jsonb, 'https://opa.berkeley.edu/uc-common-data-set', 'CS and EECS admissions are highly selective within the College of Engineering. UC GPA scale applies.', 'reach', 95, 'Berkeley, CA, USA', 'Nov 30', 'UC Application Deadline', '#1 public university globally with legendary {MAJOR} programs and direct Silicon Valley recruiting access.', 'Demonstrated intellectual depth in relevant coursework and high-impact EC narrative.', 'very_high', 'us'),
  ('rec-nyu', 'New York University (NYU)', 7.7, '2024-2025', 1390, 1550, TRUE, 31, 35, 3.7, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important","Extracurricular Activities":"Important"}'::jsonb, 'https://www.nyu.edu/about/leadership-university-administration/office-of-the-president/office-of-the-provost/institutional-research.html', 'Global campus network; NYC location is a prime recruiting hub for finance, media, and tech.', 'reach', 91, 'New York, NY, USA', 'Nov 1', 'Early Decision (ED)', 'Globally networked university at the heart of NYC''s tech and finance ecosystem — ideal for {MAJOR} students seeking immediate industry exposure.', 'Compelling personal narrative and demonstrated interest in NYC industry ecosystem.', 'high', 'us'),
  ('rec-bu', 'Boston University', 10.8, '2024-2025', 1410, 1540, TRUE, 32, 35, 3.78, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Important","Extracurricular Activities":"Important"}'::jsonb, 'https://www.bu.edu/oir/files/2024/02/CDS-2023-2024.pdf', 'Large research university in Boston with strong co-op and entrepreneurship culture.', 'reach', 89, 'Boston, MA, USA', 'Nov 1', 'Early Decision (ED)', 'Strong {MAJOR} programs in the heart of the Boston innovation corridor with deep biotech and tech employer connections.', 'Rigorous senior-year course load and a specific, authentic "Why BU" essay.', 'high', 'us'),
  ('rec-unc', 'University of North Carolina at Chapel Hill', 15.3, '2024-2025', 1330, 1520, TRUE, 30, 35, 3.9, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important","Extracurricular Activities":"Important"}'::jsonb, 'https://oira.unc.edu/data/common-data-set/', 'Highly competitive for out-of-state applicants; in-state acceptance rate significantly higher.', 'reach', 90, 'Chapel Hill, NC, USA', 'Oct 15', 'Early Action (EA)', 'Top-ranked public university with a strong {MAJOR} research pedigree and vibrant Research Triangle ecosystem.', 'Out-of-state applicants must demonstrate extraordinary achievement and clear fit.', 'high', 'us'),
  ('rec-ucsd', 'University of California, San Diego (UCSD)', 28.1, '2024-2025', 1290, 1500, TRUE, 28, 34, 3.87, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important"}'::jsonb, 'https://ir.ucsd.edu/undergrad/publications/common-data-set.html', 'Top CS and engineering school with deep biotech and defense-tech research infrastructure.', 'target', 92, 'La Jolla, CA, USA', 'Nov 30', 'UC Application Deadline', 'Tier-1 research university for {MAJOR} with proximity to San Diego''s thriving biotech and tech industry hubs.', 'UC Personal Insight Questions showing depth of academic initiative and community impact.', 'high', 'us'),
  ('rec-uva', 'University of Virginia (UVA)', 16.8, '2024-2025', 1350, 1520, TRUE, 31, 35, 3.91, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important","Extracurricular Activities":"Important"}'::jsonb, 'https://ira.virginia.edu/university-stats-facts/common-data-set', 'Highly competitive for out-of-state applicants; strong honor culture and self-governance tradition.', 'target', 91, 'Charlottesville, VA, USA', 'Nov 1', 'Early Action (EA)', 'Prestigious public flagship with strong {MAJOR} programs and a powerful DC/Northern Virginia tech recruiting corridor.', '"Why UVA" essay specificity and demonstrated intellectual engagement.', 'high', 'us'),
  ('rec-uwmadison', 'University of Wisconsin-Madison', 49.1, '2023-2024', 1290, 1480, TRUE, 27, 33, 3.76, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Important"}'::jsonb, 'https://data.wisc.edu/common-data-set/', 'Major Big Ten research university with particularly competitive direct CS admissions.', 'target', 90, 'Madison, WI, USA', 'Feb 1', 'Regular Decision', 'Top-ranked Big Ten research institution with exceptional {MAJOR} faculty and strong Midwest tech employer network.', 'Strong academic record and compelling essay demonstrating research or project initiative.', 'high', 'us'),
  ('rec-umd', 'University of Maryland, College Park', 44, '2023-2024', 1310, 1500, TRUE, 30, 34, 3.88, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Important","Extracurricular Activities":"Important"}'::jsonb, 'https://irpa.umd.edu/CDS/cds.html', 'Flagship public near Washington DC with top CS program and strong government/federal tech recruiting.', 'target', 90, 'College Park, MD, USA', 'Nov 1', 'Early Action (EA)', 'Flagship public near DC with a top-5 CS program and unmatched access to federal agencies, defense contractors, and government tech opportunities.', 'Direct-to-major CS application requires a strong quantitative profile and technical essay.', 'high', 'us'),
  ('rec-utaustin', 'University of Texas at Austin (UT Austin)', 26.6, '2024-2025', 1230, 1490, TRUE, 27, 34, 3.73, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important"}'::jsonb, 'https://reports.irris.utexas.edu/common_data_set', 'CS admission is significantly more competitive than the overall rate; top 6% TX automatic admission applies.', 'target', 91, 'Austin, TX, USA', 'Dec 1', 'Regular Decision', 'Premier public flagship in Austin''s booming tech scene. {MAJOR} graduates are heavily recruited by Tesla, Apple, Google, and Meta offices in Austin.', 'Essays demonstrating leadership and community impact are weighted heavily.', 'high', 'us'),
  ('rec-umn', 'University of Minnesota, Twin Cities', 79.8, '2024-2025', 1230, 1480, TRUE, 26, 32, 3.7, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important","Application Essay":"Important"}'::jsonb, 'https://idr.umn.edu/institutional-data/common-data-set', 'Large Big Ten research university with extensive co-op and industry partnership programs.', 'safety', 86, 'Minneapolis, MN, USA', 'Rolling', 'Rolling Admission', 'Major Big Ten research university with strong {MAJOR} programs, accessible admissions, and robust career placement in the Twin Cities tech market.', 'Meeting academic thresholds and submitting early in the rolling window.', 'high', 'us'),
  ('rec-rutgers', 'Rutgers University-New Brunswick', 66, '2023-2024', 1200, 1430, TRUE, 26, 31, 3.72, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important"}'::jsonb, 'https://www.rutgers.edu/institutional-research-and-academic-planning', 'Large state flagship in the NYC metro area with accessible admissions and strong pharma/tech industry ties.', 'safety', 85, 'New Brunswick, NJ, USA', 'Dec 1', 'Regular Decision', 'NJ flagship with strong {MAJOR} programs and proximity to NYC''s finance, pharma, and tech recruiting hubs.', 'Solid academic record and early submission for merit scholarship consideration.', 'high', 'us'),
  ('rec-oxford', 'University of Oxford', 14.1, '2024-2025', NULL, NULL, FALSE, NULL, NULL, NULL, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Admissions Test (MAT/PAT/TSA)":"Very Important","Academic Interview":"Very Important"}'::jsonb, 'https://www.ox.ac.uk/about/facts-and-figures/admissions-statistics', 'Tutorial pedagogy requiring top-percentile subject mastery, admissions assessment, and faculty interview.', 'reach', 96, 'Oxford, United Kingdom', 'Oct 15', 'UCAS Deadline', 'World-leading tutorial pedagogy in {MAJOR}. Demands top-percentile subject mastery and admissions test scores.', 'Oxbridge admissions test (MAT/PAT/TSA) score and rigorous academic interview.', 'very_high', 'uk'),
  ('rec-cambridge', 'University of Cambridge', 16.4, '2024-2025', NULL, NULL, FALSE, NULL, NULL, NULL, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Subject Written Assessment":"Very Important","Academic Interview":"Very Important"}'::jsonb, 'https://www.undergraduate.study.cam.ac.uk/apply/statistics', 'Supervision system emphasizing deep mathematical and logical problem solving from day one.', 'reach', 95, 'Cambridge, United Kingdom', 'Oct 15', 'UCAS Deadline', 'Premier academic supervision system and direct subject focus from matriculation.', 'Subject-specific written assessment and mathematical problem-solving depth.', 'very_high', 'uk'),
  ('rec-ucl', 'University College London (UCL)', 25, '2024-2025', NULL, NULL, FALSE, NULL, NULL, NULL, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Application Essay":"Very Important"}'::jsonb, 'https://www.ucl.ac.uk/data-protection/data-protection-overview/ucl-student-data', 'Global top 10 university with rich interdisciplinary research centers in central London.', 'target', 91, 'London, United Kingdom', 'Jan 31', 'UCAS Standard', 'Global top 10 university with rich interdisciplinary research centers.', 'UCAS Personal Statement academic alignment and IELTS score clearance.', 'high', 'uk'),
  ('rec-edinburgh', 'University of Edinburgh', 33, '2023-2024', NULL, NULL, FALSE, NULL, NULL, NULL, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important"}'::jsonb, 'https://www.ed.ac.uk/student-recruitment/admissions-statistics', '4-year Scottish curriculum allowing broad flexibility before honors specialization.', 'target', 89, 'Edinburgh, Scotland', 'Jan 31', 'UCAS Standard', '4-year Scottish honors system allowing broader academic exploration.', 'Consistent high school transcript and subject prerequisite grades.', 'high', 'uk'),
  ('rec-manchester', 'University of Manchester', 56, '2023-2024', NULL, NULL, FALSE, NULL, NULL, NULL, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important"}'::jsonb, 'https://www.manchester.ac.uk/discover/facts-figures/', 'Prestigious Russell Group university with high international student representation.', 'safety', 87, 'Manchester, United Kingdom', 'Jan 31', 'UCAS Standard', 'Prestigious Russell Group university. Fits your current academic standing while providing room for high-caliber growth in {MAJOR}.', 'Meeting minimum IELTS entry score and consistent year-12 subject performance.', 'moderate', 'uk'),
  ('rec-sheffield', 'University of Sheffield', 68, '2023-2024', NULL, NULL, FALSE, NULL, NULL, NULL, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important"}'::jsonb, 'https://www.sheffield.ac.uk/about/facts', 'Leading research institution with modern engineering facilities and direct entry schemes.', 'safety', 84, 'Sheffield, UK', 'Jan 31', 'UCAS Standard', 'Strong technical and research facilities with accessible direct conditional entry schemes.', 'UCAS Personal Statement focus and meeting subject prerequisites.', 'high', 'uk'),
  ('rec-sussex', 'University of Sussex', 78, '2023-2024', NULL, NULL, FALSE, NULL, NULL, NULL, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important"}'::jsonb, 'https://www.sussex.ac.uk/about/facts-and-figures', 'Supportive campus community located near Brighton with diverse degree programs.', 'target', 86, 'Brighton, UK', 'Jan 31', 'UCAS Standard', 'Solid international student community with strong industry links and accessible admissions.', 'Verified high school graduation certificate and IELTS clearance.', 'high', 'uk'),
  ('rec-portsmouth', 'University of Portsmouth', 86, '2023-2024', NULL, NULL, FALSE, NULL, NULL, NULL, '{"Academic GPA":"Very Important"}'::jsonb, 'https://www.port.ac.uk/about-us/facts-and-figures', 'Direct conditional entry and foundation options for international students.', 'safety', 88, 'Portsmouth, UK', 'Rolling', 'UCAS Direct', 'High student satisfaction and supportive foundation/direct degree programs.', 'Standard academic completion and basic English proficiency.', 'high', 'uk'),
  ('rec-utoronto', 'University of Toronto', 43, '2023-2024', NULL, NULL, FALSE, NULL, NULL, NULL, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Supplementary Application":"Very Important"}'::jsonb, 'https://data.utoronto.ca/cudo/', '#1 university in Canada with top-tier research output and substantial co-op opportunities.', 'reach', 94, 'Toronto, ON, Canada', 'Jan 15', 'Early Consideration', '#1 university in Canada with massive research output and co-op opportunities.', 'Supplementary Application video/essay response and IELTS 7.0+ standard.', 'very_high', 'canada'),
  ('rec-ubc', 'University of British Columbia (UBC)', 56, '2024-2025', NULL, NULL, FALSE, NULL, NULL, NULL, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Personal Profile":"Very Important"}'::jsonb, 'https://pair.ubc.ca/student-data/', 'Personal Profile essays evaluated alongside rigorous high school coursework.', 'reach', 92, 'Vancouver, BC, Canada', 'Jan 15', 'Standard Deadline', 'Top international faculty, Pacific Rim innovation hubs, and high quality of life.', 'Personal Profile essays showcasing extracurricular engagement and leadership.', 'high', 'canada'),
  ('rec-waterloo', 'University of Waterloo', 53, '2023-2024', NULL, NULL, FALSE, NULL, NULL, NULL, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important","Admission Information Form (AIF)":"Very Important","Euclid Math Contest":"Important"}'::jsonb, 'https://uwaterloo.ca/institutional-analysis-planning/university-data', 'World-renowned co-op program with premier software engineering recruitment.', 'target', 93, 'Waterloo, ON, Canada', 'Feb 1', 'Standard Deadline', 'World-renowned Co-Op program connecting students directly to Silicon Valley tech.', 'Admission Information Form (AIF) and Euclid Math Contest results.', 'very_high', 'canada'),
  ('rec-sfu', 'Simon Fraser University (SFU)', 65, '2023-2024', NULL, NULL, FALSE, NULL, NULL, NULL, '{"Rigor of secondary school record":"Very Important","Academic GPA":"Very Important"}'::jsonb, 'https://www.sfu.ca/irp.html', 'Solid applied computing, engineering, and business tracks across 3 Metro Vancouver campuses.', 'safety', 86, 'Burnaby, BC, Canada', 'Jan 31', 'Standard Deadline', 'Recognized Canadian institution with strong computing and business curriculum.', 'Submitting strong senior-year marks and meeting IELTS cutoff.', 'moderate', 'canada'),
  ('rec-uvic', 'University of Victoria', 64, '2024-2025', NULL, NULL, FALSE, NULL, NULL, NULL, '{"Academic GPA":"Very Important"}'::jsonb, 'https://www.uvic.ca/institutionalplanning/institutional-data/index.php', 'Comprehensive university on Vancouver Island with supportive international student tracks.', 'target', 86, 'Victoria, BC, Canada', 'Feb 28', 'Standard Deadline', 'High student satisfaction and accessible comprehensive degree tracks.', 'Meeting general high school average requirements and IELTS clearance.', 'high', 'canada'),
  ('rec-snu', 'Seoul National University', 20, '2024-2025', NULL, NULL, FALSE, NULL, NULL, 3.9, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important","Suneung (CSAT) Score":"Very Important","Extracurricular Activities":"Important"}'::jsonb, 'https://admission.snu.ac.kr', 'Top-ranked national university in Korea. Admission is highly competitive and primarily based on CSAT and school records. International student quota separate from domestic.', 'reach', 95, 'Seoul, South Korea', 'Sep 11', 'Regular Admission', 'Korea''s most prestigious university with world-class {MAJOR} research output and strong ties to Samsung, LG, and Kakao for industry placement.', 'Outstanding CSAT scores and school record; international applicants judged on SAT/ACT plus high school transcripts.', 'very_high', 'korea'),
  ('rec-kaist', 'KAIST (Korea Advanced Institute of Science and Technology)', 23, '2023-2024', NULL, NULL, FALSE, NULL, NULL, 3.92, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important","Research / Projects":"Important","English Proficiency":"Important"}'::jsonb, 'https://admission.kaist.ac.kr', 'Premier STEM-focused institution, tuition-free for domestic students. Highly competitive for international applicants with strong STEM background.', 'reach', 93, 'Daejeon, South Korea', 'Sep 15', 'International Admission', 'Asia''s leading STEM university for {MAJOR}, with tuition scholarships and direct pipelines into Korea''s semiconductor and AI industries.', 'Demonstrated research experience and strong quantitative scores are weighted heavily for international applicants.', 'very_high', 'korea'),
  ('rec-yonsei', 'Yonsei University', 16, '2023-2024', NULL, NULL, FALSE, NULL, NULL, 3.85, '{"Academic GPA":"Very Important","Application Essay":"Very Important","Extracurricular Activities":"Important","English Proficiency":"Important"}'::jsonb, 'https://admission.yonsei.ac.kr', 'Part of the SKY (Seoul National, Korea, Yonsei) elite trio. Underwood International College offers full English-language programs attractive to international students.', 'reach', 91, 'Seoul, South Korea', 'Oct 1', 'International Admission', 'Elite SKY university with Underwood International College — full English-medium {MAJOR} programs and a vibrant Seoul campus with global alumni network.', 'Strong GPA, essays articulating Korea-specific goals, and English proficiency (TOEFL 100+ recommended).', 'high', 'korea'),
  ('rec-korea-univ', 'Korea University', 17, '2023-2024', NULL, NULL, FALSE, NULL, NULL, 3.82, '{"Academic GPA":"Very Important","Application Essay":"Important","Extracurricular Activities":"Important"}'::jsonb, 'https://ipsi.korea.ac.kr', 'Third member of the SKY group. Strong business and law schools; growing international programs in English.', 'reach', 89, 'Seoul, South Korea', 'Oct 1', 'International Admission', 'SKY-tier university with a strong {MAJOR} faculty and deep connections to Korean conglomerates (chaebol) for career placement.', 'Academic record and motivation essay are key; TOPIK not required for English-track applicants.', 'high', 'korea'),
  ('rec-postech', 'POSTECH (Pohang University of Science and Technology)', 19, '2023-2024', NULL, NULL, FALSE, NULL, NULL, 3.9, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important","Research / Projects":"Very Important"}'::jsonb, 'https://admission.postech.ac.kr', 'Highly selective small STEM university backed by POSCO. Consistently ranked among Asia''s top 10 for engineering and materials science.', 'reach', 90, 'Pohang, South Korea', 'Sep 20', 'Regular Admission', 'Korea''s MIT equivalent for {MAJOR} with intensive research culture, small class sizes, and industry backing from POSCO Steel.', 'Research portfolio and quantitative ability are critical; small cohort means every applicant is closely evaluated.', 'very_high', 'korea'),
  ('rec-sungkyunkwan', 'Sungkyunkwan University (SKKU)', 38, '2023-2024', NULL, NULL, FALSE, NULL, NULL, 3.7, '{"Academic GPA":"Very Important","English Proficiency":"Important","Application Essay":"Important"}'::jsonb, 'https://admission.skku.edu', 'Samsung-affiliated university with strong engineering and natural sciences. Good English-medium programs and scholarship opportunities for international students.', 'target', 86, 'Seoul / Suwon, South Korea', 'Oct 15', 'International Admission', 'Samsung-backed university with strong {MAJOR} programs, generous merit scholarships, and direct industry ties to Samsung Electronics and affiliated companies.', 'Strong academic record and TOEFL/IELTS score; Samsung scholarship applicants need additional recommendation.', 'high', 'korea'),
  ('rec-tum', 'Technical University of Munich (TUM)', 8, '2023-2024', NULL, NULL, FALSE, NULL, NULL, 3.9, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important","Research / Projects":"Important","Application Essay":"Important"}'::jsonb, 'https://www.tum.de/en/studies/applying', 'Germany''s top-ranked STEM university and one of Europe''s leading research institutions. Highly competitive for international Master''s applicants; Bachelor''s admission varies by program.', 'reach', 95, 'Munich, Germany', 'May 31', 'Winter Semester', 'Germany''s #1 STEM university for {MAJOR} with world-class research, no tuition fees for most programs, and strong industry links to BMW, Siemens, and MAN.', 'Exceptionally high GPA (equivalent 1.0–1.5 on German scale) and relevant academic background; motivational letter is decisive for international applicants.', 'very_high', 'germany'),
  ('rec-lmu', 'Ludwig Maximilian University of Munich (LMU)', 18, '2024-2025', NULL, NULL, FALSE, NULL, NULL, 3.88, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important","Application Essay":"Important"}'::jsonb, 'https://www.lmu.de/en/study/international-applicants/', 'Germany''s highest-ranked comprehensive university. Excellence Initiative winner with broad academic portfolio. Competitive NC cutoffs for popular programs.', 'reach', 92, 'Munich, Germany', 'May 15', 'Winter Semester', 'Germany''s premier comprehensive research university — ideal for {MAJOR} students seeking a balance of rigorous academics and Munich''s vibrant cultural and tech scene.', 'High academic GPA and German language proficiency (B2/C1) for German-taught programs; English-taught Master''s require TOEFL/IELTS.', 'very_high', 'germany'),
  ('rec-heidelberg', 'Heidelberg University', 20, '2023-2024', NULL, NULL, FALSE, NULL, NULL, 3.85, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important","Language Proficiency":"Important"}'::jsonb, 'https://www.uni-heidelberg.de/en/study/international', 'Germany''s oldest university (est. 1386) and a leading Excellence Initiative institution. Especially strong in natural sciences, medicine, and humanities.', 'reach', 90, 'Heidelberg, Germany', 'May 15', 'Winter Semester', 'Germany''s oldest university with a prestigious research legacy — strong fit for {MAJOR} students interested in rigorous academic tradition and European research networks.', 'Strong academic record; German language proficiency required for most undergraduate programs.', 'high', 'germany'),
  ('rec-kit', 'Karlsruhe Institute of Technology (KIT)', 25, '2023-2024', NULL, NULL, FALSE, NULL, NULL, 3.82, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important","Research / Projects":"Important"}'::jsonb, 'https://www.kit.edu/english/studying.php', 'Merger of former University of Karlsruhe and Forschungszentrum Karlsruhe. One of Germany''s top engineering schools with significant research funding.', 'target', 88, 'Karlsruhe, Germany', 'May 15', 'Winter Semester', 'Top German engineering school for {MAJOR} with a dual university-research center model, strong industry partnerships, and no tuition fees.', 'Good GPA in relevant subjects; some programs require German language certification.', 'high', 'germany'),
  ('rec-rwth', 'RWTH Aachen University', 23, '2024-2025', NULL, NULL, FALSE, NULL, NULL, 3.8, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important","Application Essay":"Important"}'::jsonb, 'https://www.rwth-aachen.de/go/id/mkq/lidx/1', 'Germany''s largest technical university and one of Europe''s leading engineering schools. Exceptionally strong in mechanical and electrical engineering.', 'target', 87, 'Aachen, Germany', 'May 15', 'Winter Semester', 'Europe''s top technical university for engineering — {MAJOR} graduates are heavily recruited by automotive giants like Ford, BMW, and technology firms near the Aachen–Brussels–Eindhoven tech triangle.', 'Strong math and science GPA; German proficiency required for most undergraduate tracks.', 'high', 'germany'),
  ('rec-fu-berlin', 'Freie Universität Berlin', 60, '2024-2025', NULL, NULL, FALSE, NULL, NULL, 3.75, '{"Academic GPA":"Very Important","Application Essay":"Important","Language Proficiency":"Important"}'::jsonb, 'https://www.fu-berlin.de/en/studium/international/index.html', 'One of Germany''s 11 Universities of Excellence. Particularly strong in humanities, social sciences, and life sciences. Berlin location offers unique cultural and startup ecosystem.', 'target', 85, 'Berlin, Germany', 'Jun 1', 'Winter Semester', 'Berlin''s top research university for {MAJOR} with an international atmosphere, no tuition fees, and access to Berlin''s booming startup and tech ecosystem.', 'Solid GPA and language certification (German or English depending on program).', 'high', 'germany'),
  ('rec-peking', 'Peking University (PKU)', 20, '2024-2025', NULL, NULL, FALSE, NULL, NULL, 3.95, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important","Application Essay":"Very Important","Chinese Language Proficiency":"Important"}'::jsonb, 'https://admissions.pku.edu.cn/en/', 'China''s most prestigious comprehensive university. International students admitted through a separate process; English-taught programs available in select departments.', 'reach', 96, 'Beijing, China', 'Apr 30', 'International Admission', 'China''s most elite university for {MAJOR}, with unrivaled access to Beijing''s technology and government sectors, and global alumni spanning top research institutions worldwide.', 'Outstanding academic record; HSK proficiency (Level 4+) required for Chinese-medium programs; English-taught programs need strong TOEFL/IELTS.', 'very_high', 'china'),
  ('rec-tsinghua', 'Tsinghua University', 20, '2024-2025', NULL, NULL, FALSE, NULL, NULL, 3.95, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important","Research / Projects":"Very Important","Application Essay":"Important"}'::jsonb, 'https://www.tsinghua.edu.cn/en/Admissions.htm', 'China''s top STEM and engineering university, consistently ranked in global top 25. International students admitted separately; strong English-medium engineering programs.', 'reach', 96, 'Beijing, China', 'Apr 30', 'International Admission', 'Asia''s top engineering university for {MAJOR} — the alma mater of a majority of China''s tech leaders, with world-class labs and direct pipelines into Huawei, ByteDance, and Tencent.', 'Near-perfect academic record and demonstrable STEM achievement; international applicants screened via portfolio and interview.', 'very_high', 'china'),
  ('rec-fudan', 'Fudan University', 32, '2024-2025', NULL, NULL, FALSE, NULL, NULL, 3.88, '{"Academic GPA":"Very Important","Application Essay":"Very Important","Language Proficiency":"Important","Extracurricular Activities":"Important"}'::jsonb, 'https://www.fudan.edu.cn/en/channels/view/108/', 'Top comprehensive university in Shanghai, particularly strong in medicine, economics, and liberal arts. More international-friendly than Beijing counterparts.', 'reach', 92, 'Shanghai, China', 'Apr 30', 'International Admission', 'Shanghai''s premier comprehensive university for {MAJOR} — strong global partnerships, English-medium programs, and access to China''s financial and commerce capital.', 'Strong GPA and personal statement; Shanghai location makes English-language programs more accessible than Beijing peers.', 'very_high', 'china'),
  ('rec-sjtu', 'Shanghai Jiao Tong University (SJTU)', 32, '2024-2025', NULL, NULL, FALSE, NULL, NULL, 3.87, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important","Research / Projects":"Important"}'::jsonb, 'https://en.sjtu.edu.cn/admissions/', 'Top engineering and sciences university in Shanghai. Known internationally for its Academic Ranking of World Universities (ARWU/Shanghai Rankings), which it founded.', 'reach', 91, 'Shanghai, China', 'Apr 30', 'International Admission', 'China''s leading engineering and technology university for {MAJOR}, with strong research output, multiple English-medium programs, and a Shanghai location offering global career access.', 'High GPA with STEM focus; international applicants assessed on transcripts, standardized test scores, and research background.', 'very_high', 'china'),
  ('rec-zhejiang', 'Zhejiang University', 15, '2023-2024', NULL, NULL, FALSE, NULL, NULL, 3.85, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important","Application Essay":"Important"}'::jsonb, 'https://www.zju.edu.cn/english/2023/0901/c19573a2783218/page.htm', 'Located in Hangzhou near Alibaba HQ. Comprehensive C9 League university with strong engineering, agriculture, and medicine programs.', 'reach', 89, 'Hangzhou, China', 'Apr 15', 'International Admission', 'C9 League university in Hangzhou — proximity to Alibaba and a thriving tech ecosystem makes it a strong choice for {MAJOR} students targeting China''s e-commerce and cloud sectors.', 'Strong academic record; some English-taught programs available; Chinese proficiency advantageous.', 'high', 'china'),
  ('rec-ustc', 'University of Science and Technology of China (USTC)', 10, '2023-2024', NULL, NULL, FALSE, NULL, NULL, 3.9, '{"Academic GPA":"Very Important","Rigor of secondary school record":"Very Important","Research / Projects":"Very Important"}'::jsonb, 'https://en.ustc.edu.cn/2023/0608/c18062a592098/page.htm', 'Elite C9 League STEM university founded by the Chinese Academy of Sciences. Exceptional for physics, math, and computer science. Lower profile internationally but domestic ranking rivals Tsinghua/PKU for STEM.', 'reach', 92, 'Hefei, China', 'Apr 30', 'International Admission', 'China''s most research-intensive STEM university for {MAJOR} — affiliated with the Chinese Academy of Sciences, offering unparalleled access to national research labs and quantum computing initiatives.', 'Exceptional quantitative ability and research background; among the most selective STEM programs in China.', 'very_high', 'china'),
  ('rec-carleton', 'Carleton University', 60, '2024-2025', NULL, NULL, FALSE, NULL, NULL, NULL, '{"Academic GPA":"Very Important"}'::jsonb, 'https://carleton.ca/oirp/institutional-data/', 'Capital city university with reliable international admissions and practical co-op programs.', 'safety', 88, 'Ottawa, ON, Canada', 'Mar 1', 'Rolling Intake', 'Capital city university with reliable international admissions and co-op options.', 'Transcripts and standard language qualification.', 'high', 'canada')
ON CONFLICT (school_id) DO UPDATE SET
  name                        = EXCLUDED.name,
  official_acceptance_rate    = EXCLUDED.official_acceptance_rate,
  acceptance_rate_source_year = EXCLUDED.acceptance_rate_source_year,
  sat_25th                    = EXCLUDED.sat_25th,
  sat_75th                    = EXCLUDED.sat_75th,
  avg_enrolled_gpa_unweighted = EXCLUDED.avg_enrolled_gpa_unweighted,
  cds_factor_weights          = EXCLUDED.cds_factor_weights,
  notes                       = EXCLUDED.notes,
  updated_at                  = NOW();

-- Verify
SELECT COUNT(*) AS total_schools FROM school_profiles;
